### ISSUE TITLE
Gross income transactions

### ISSUE THREAD

**Issue by afhampton** [shanewalters/qif#1]
Hi Shane. Does this library support the processing of Gross income transactions, income taxes and deductions, tax labeling, etc.?

**Comment by shanewalters** [comment]
The short answer is: if it's supported in the file format specification, then yes. There are parts of your question, however, that warrant a more detailed answer.

The [file format specification](http://web.archive.org/web/20100222214101/http://web.intuit.com/support/quicken/docs/d_qif.html) is fairly bare bones. With that in mind:
* It supports transactions of various types (specifically bank account, cash account, credit card, investment account, asset account, and liability account).
* It also supports limited tax information. Specifically, it allows you to define categories as tax related or not, and associate a tax schedule to the category. The term "categories" stems from Quicken's use of the word--how to categorize expenses in your transaction list.

If you're looking for a robust medium to transfer tax details, this may not be the best option. This utility is offered to enable developers a more convenient way to work with these files. You should note that [Intuit has specifically deprecated the use of QIF in favor of QFX.](http://web.intuit.com/personal/quicken/qif/).
