### ISSUE TITLE
Wrong encoding for importing into Quicken

### ISSUE THREAD

**Issue by LucasMetal** [shanewalters/qif#2]
Hi!

First of all, thanks for this great library!!

I'm from Argentina and when generating QIF files that contains words with tilde (ie: "día", "jamón", etc.) and then importing them into Quicken, the tildes are not correctly imported.

I tracked this down to the encoding of the generated file, the StreamReader defaults to UTF8 and Quicken seems to be using ANSI.

I solved it quickly by adding an optional parameter for the encoding to the export method, and defaulting to UTF8 to maintain backwards compatibility.
So in my code I'm passing Encoding.Default, and that solves my problem.

If you want I can send a PR maybe? 
You can take a look at my changes here (ignore the changes in CashLogic.cs, I will open another issue for that): https://github.com/shanewalters/qif/compare/master...LucasMetal:master
Note that I didn't modify the QIFDomWrapper since I don't have experience with COM, maybe you can help me with that or you can do it after merging my changes.

Looking forward to your reply, thanks for your time.
-Lucas

**Comment by shanewalters** [comment]
Lucas,

Go ahead and open a PR for the encoding issue. I'll approve it quickly.

-Shane

**Comment by shanewalters** [comment]
Give the size of changes, I went ahead and implemented this. See commit https://github.com/shanewalters/qif/commit/7e27798f8c8ea8197c52cb42c9575ff8a5b4479c.
