### ISSUE TITLE
Wrong date and decimal format for importing into Quicken

### ISSUE THREAD

**Issue by LucasMetal** [shanewalters/qif#3]
Hi!

As I said in my previous issue, thanks again for this great lib ;)

Unluckily when importing the QIF files that the lib generates into Quicken, the dates and decimal values are not correctly interpreted. 
I'm in Argentina and my culture uses "DD-MM-YYYY" for dates and comma as decimal separator, and it seems like Quicken doesn't take into account the culture of the system, and always use the en-US culture. And as the lib is using the CurentCulture for decimals and a simple .ToShortDateString() for dates, it doesn't play well with Quicken.

I don't know what would be the correct solution because the README of the project says *"All transactions present in the DOM are written according to the QIF file format specification. Dates and numbers should be written according to globalization standards."*.
But when checking the ["official" format documentation (according to Wikipedia)](http://web.archive.org/web/20100222214101/http://web.intuit.com/support/quicken/docs/d_qif.html) they use `D8/25/93` as an example date, so no globalization there, and that's exactly what Quicken is considering.

I did a quick hack for testing my ideas and it works OK with Quicken 2015, but it's not complete of course. In fact it should be using the InvariantCulture also for the dates, and that would be enough I guess (as I mentioned, it was a quick hack to get the ball rolling).
You can check the changes in CashLogic.cs (ignore the other changes please, they are mentioned in my other issue):
https://github.com/shanewalters/qif/compare/master...LucasMetal:master

Would it be reasonable to use InvariantCulture in every place (for decimals, dates, etc)? Intuit is the creator of the format and they seem to not care about globalization (it's OK for me :P).
Or maybe being able to indicate the culture when exporting?

I feel like I'm missing something, can you give me a hand with this? I would like to use the lib from Nuget directly and not having a custom version only for my needs :(

Thanks!
-Lucas

**Comment by shanewalters** [comment]
Commit https://github.com/shanewalters/qif/commit/009ddd5f926288f245d9153ab30175e53b6bdcb3 should address this issue. I created a configuration based parsing approach. Since it's new, my main concern was backwards compatibility. Have a look at [Configuration.cs] (https://github.com/shanewalters/qif/blob/master/QifApi/Config/Configuration.cs). That should allow you to explicitly set parsing formats and styles; otherwise, it defaults to classical behavior.
